[rgt-settings]
# 0: electrical OR 1: mechanical
response_type = 1
# 0: static OR 1: dynamic
param_type = 0
# 0.0 to 1.0
selected_vertex_proportion = 0.05

[dc-response]
# TB BT, LR, RL
potential_direction = TB
potential_magnitude = 100
potential_frequency = 0.000000000001
resistivity = 1.0
capacitance = 0.000000000001
inductance = 0.00000000000000000001
leak_resistivity = 1000000000

[mechanical-response]
# left, right, top, bottom
pinned_direction = bottom
displacement_direction = top
