[rgt-settings]
# 0: static OR 1: dynamic
response_type = 0
selected_vertex_proportion = 0.05

[dc-response]
# TB BT, LR, RL
potential_direction = TB
potential_magnitude = 100
potential_frequency = 0.000000000001
resistivity = 1.0
capacitance = 0.000000000001
inductance = 0.00000000000000000001
leak_resistivity = 1000000000

[mechanical-response]
cartesian_direction = 0
use_smallest_boolean = 1
